# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terragrunt-layers-example"
    dynamodb_table = "tg-state-lock"
    encrypt        = true
    key            = "layer1/compute/terraform.tfstate"
    region         = "us-east-1"
  }
}
